
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 02 14:09:33 AST 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 8;
  public static final int Double = 10;
  public static final int Llave_c = 30;
  public static final int Op_booleano = 7;
  public static final int Llave_a = 29;
  public static final int If = 17;
  public static final int T_dato = 3;
  public static final int Else = 18;
  public static final int Long = 11;
  public static final int While = 20;
  public static final int Division = 26;
  public static final int Int = 15;
  public static final int Cadena = 16;
  public static final int Float = 9;
  public static final int Parentesis_c = 28;
  public static final int Parentesis_a = 27;
  public static final int For = 21;
  public static final int EOF = 0;
  public static final int P_coma = 32;
  public static final int error = 1;
  public static final int Integer = 13;
  public static final int Linea = 2;
  public static final int Private = 14;
  public static final int Op_atribucion = 4;
  public static final int ERROR = 35;
  public static final int Do = 19;
  public static final int Protected = 12;
  public static final int Identificador = 33;
  public static final int Resta = 24;
  public static final int Multiplicacion = 25;
  public static final int Op_incremento = 5;
  public static final int Numero = 34;
  public static final int Suma = 23;
  public static final int Main = 31;
  public static final int Igual = 22;
  public static final int Comillas = 6;
}

